name = Sample App
description = Sample App is used to show how apps work
machine_name = sample_app
version = 1.0-alpha1
downloadable = sample_app 1.0-alpha1
author = Vejle Idrætshøjskole
author_url = http://vih.dk
screenshots[] = screenshot.jpg
logo = logo.png
dependencies[ctools] = ctools 1.0-alpha4
downloadables[sample_app 1.0-alpha1] = http://vih.dk/sample-app-7.x-1.0-alpha1.tar.gz
downloadables[ctools 1.0-alpha4] = http://ftp.drupal.org/files/projects/ctools-7.x-1.0-alpha4.tar.gz
